package enums;

public enum Category {
	STUDENT, LISTENER, APEC_STUDENT, FS_STUDENT, EXCHANGE_STUDENT, LISTENER_UOL, CONDITIONALLY_ENROLLED, STUDENT_SOCIAL_CATEGORY1_2, STUDENT_SOCIAL_CATEGORY3_4
}
